### ISSUE TITLE
Please add support for ES6 Immediately-invoked function

### ISSUE THREAD

**Issue by lawlietmester** [endel/js2php#22]
Please add support for ES6 Immediately-invoked function:

```
( () => {
  // some code here
})();
```

**Comment by 2pha** [comment]
How would that work? PHP does not have IIFE

**Comment by lawlietmester** [comment]
call_user_func( function(){

});

**Comment by endel** [comment]
Hi @lawlietmester, sorry the delay to answer. For some reason, I wasn't receiving email updates about this repository. 

Version `0.1.3` now supports IIFE's as you suggested.

Check the fixture: 
- [JavaScript input](https://github.com/endel/js2php/blob/master/test/fixtures/iife.js)
- [PHP output](https://github.com/endel/js2php/blob/master/test/fixtures/iife.php)
