### ISSUE TITLE
JS string concat issue

### ISSUE THREAD

**Issue by karthick4in** [endel/js2php#26]
Hi i  try to print var value with some string. 

**js code**
function print(a)
{
  print("var a value "+a+"");
}
print(10);

**php convert code.**
< ? php
function print($a) {
**print("var a value " + $a + "");**
}
print(10);

**Error**
print("var a value " + $a + "");
expect - **print("var a value " . $a . "");**

**Comment by endel** [comment]
@2pha fixed this on #31 👏  version `0.1.1` has been released.
